on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 22.20.0
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run w:check
      - run: pnpm run w:typecheck
      - run: pnpm run w:build
